### ISSUE TITLE
Getting last inserted ID from database

### ISSUE THREAD

**Issue by viviosoft** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#38] opened 2012-08-04 11:41 UTC
Hello -

Need to get the last insert ID from the database.  This is how I'm approaching it. Seems to be the common approach from other sources on the web for WebKit.  However, it may not work in our case due to how we are inserting items in a native database.  Although, it may work and I'm not doing something right.  Thanks for any help you can provide.

```
function setInvoiceDetails(sId, invDate, invStatus, repNum, callback){

    AVDB.transaction(function (tx) {
        tx.executeSql('INSERT INTO invoice_details (invoiceStatus, sNumber, invoiceDate, repNumber) VALUES (?, ?, ?, ?)',
            [invStatus, sId, invDate, repNum],
            function (tx, results) {
                // Get invoice id so we can use it for adding items to newly created invoice
                var invId = results.insertId;
                callback(invId);

            }

        );
    });

}
```

**Comment by brody2consult** [comment] 2012-08-04 11:59
~~I have already put~~ this problem _was already reported_ in bug #18. I will work on this one today.

**Comment by brody2consult** [comment] 2012-08-04 12:47
@viviosoft I have already updated the test program under the Android subsection of Installing in README.md that reproduces this problem. I would like to close this issue as a duplicate of #18 and move all remaining discussion to #18.

**Closed as completed** 2012-08-04 12:47 UTC
Labels: bug, duplicate

**Comment by brody2consult** [comment] 2012-08-04 13:11
@viviosoft can you verify if this is fixed for you?
