### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by scottbuckel** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#34] opened 2012-07-11 20:50 UTC
Hello, I feel the the documentation is extremely limited.  I'm not sure how to use my own .sqlite database from within the plugin.  If anyone has any hints that would be great.  The reason I have to use this plugin is because I have a database of about 50k records and native HTML5/JS was too slow.

**Comment by brody2consult** [comment] 2012-08-08 19:28
This is a duplicate of #10 and will now be closed. Very important information at: http://gauravstomar.blogspot.com/2011/08/prepopulate-sqlite-in-phonegap.html needs to be adapted for both iOS and Android versions of this plugin.

**Closed as completed by brody2consult** 2012-08-08 19:28 UTC
Labels: duplicate

**Comment by scottbuckel** [comment] 2012-08-08 19:30
That information is very out of date.  I blogged about it here and will post a follow up sometime soon:
http://www.raymondcamden.com/index.cfm/2012/7/27/Guest-Blog-Post-Shipping-a-populated-SQLite-DB-with-PhoneGap

**Comment by brody2consult** [comment] 2012-08-08 19:46
Thanks @sebumd I quoted this into #10 and plan to put the link into the README for Android very soon.
